export const PASSENGER_ACCESS_TOKEN = "PASSENGER_ACCESS_TOKEN";

export const PASSENGER_REFRESH_TOKEN = "PASSENGER_REFRESH_TOKEN";

export const PASSENGER_ROUTE_PREFIX = "/passenger";

export const DRIVER_ACCESS_TOKEN = "DRIVER_ACCESS_TOKEN";

export const DRIVER_REFRESH_TOKEN = "DRIVER_REFRESH_TOKEN";

export const DRIVER_ROUTE_PREFIX = "/driver";

export const RYDES_PASSENGER_USER_TYPE = "PASSENGER";

export const RYDES_DRIVER_USER_TYPE = "DRIVER";
